* IronYard

This is my root directory for my time at IronYard.


** D01

   We discussed some stuff


** DAY 02

*** DONE Quiz
    Quiz a user on trivia relating to numbers pulled from the [[http://numbersapi.com/][Numbers
    API]].
*** DONE BMI_CALC
    Calculates BMI based on user input according to the formula found
    [[http://en.wikipedia.org/wiki/Body_mass_index][here]].


** Day 3 - January 7th 2015

   Choose one! 

*** DONE Assignment 1:

    Create a number guessing game. Game should pick a random number
    between 1 and 100 and ask you for a guess. If the guess is less
    than the number, inform the user and let them guess again. If the
    guess is greater than the number, inform the user and let them
    guess again. If the guess is correct, inform the user and quit.

    Bonus: write the opposite program: you, the user, pick a number
    between 1 and 100. The computer has to guess the number. You tell
    it whether it's too high, too low, or right on after each
    guess. The computer gets five guesses.

*** TODO Assignment 2:

    Create Blackjack. Use numbers 1-11 for cards instead of creating
    an entire deck! I want to be able to split on double cards and
    play both hands.

    Bonus: create a dealer for the blackjack game. He doesn't have to
    split.

    | Components | Desc                     |
    |------------+--------------------------|
    | deck       | - standard deck of cards |
    |            | - next card              |
    |------------+--------------------------|
    | player     | - bankroll               |
    |            | - bet                    |
    |            | - cards                  |
    |            | - hit / stay             |
    |            | - split                  |
    |------------+--------------------------|
    | dealer     | - is_busted?             |
    |------------+--------------------------|
    |            |                          |

*** TODO Assignment 3:

    Finish tic tac toe. Check for wins. Tell the user to move again if
    they choose a spot that is already taken.

*** TODO Extra bonus.

    Do all of the above - Will buy someone a beer on Friday if they do
    all of the above.


** TODO Day 4 - Jan 8th 2015

   Horse racing game. (More complicated because they have Friday and
   the whole weekend)

*** Rules:

   - Must use at least two classes Must have at least 4 horses (All
     horses can NOT be different classes!
   - User input must affect at least one horse's speed Must out put
     the horses' paths (even as simple as "---'horse 1'") as race
     progresses

*** Goals:

    - classes
    - methods
    - passing arguments to methods
    - thinking about the design and how classes interface with each
      other
    - DRYness
    - making a complete & interesting & good program
